[package]
name = "dinnerlog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20.0"
mysql = "24.0.0"
time = { version = "0.3.23", features = ["macros"] }
uuid = "1.4.0"
